name: Build LaTeX PDF

on:
  workflow_dispatch:
  push:
    paths:
      - 'resume/**'
      - ".github/workflows/build-latex.yml"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install LaTeX
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive-latex-base texlive-latex-extra jq curl

      - name: Compile PDF
        working-directory: resume
        run: pdflatex -interaction=nonstopmode 2026-fullstack.tex

      - name: Upload PDF Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Resume-PDF
          path: resume/2026-fullstack.pdf

      - name: Upload to tmpfiles.org
        id: tmpfiles
        working-directory: resume
        run: |
          response=$(curl -s -F "file=@2026-fullstack.pdf" https://tmpfiles.org/api/v1/upload)
          url=$(echo $response | jq -r '.data.url')
          echo "Uploaded to: $url"
          echo "PDF_DESC_URL=$url" >> $GITHUB_ENV

      - name: Notify Slack
        if: always()
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{"text":"Resume PDF Build Complete! Download here: '"$PDF_DESC_URL"'"}' ${{ secrets.SLACK_WEBHOOK_URL }}

